mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as users_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('users/', include('users.urls')),
    path('register/', users_views.register, name='register'),
    path('login/', users_views.login_view, name='login'),
    path('logout/', users_views.logout_view, name='logout'),
    path('profile/', users_views.profilepage, name='profile'),
]

urlpatterns += [] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/products/urls.py
from django.urls import path, include
from products import views

app_name = 'products'

urlpatterns = [
    
    # function based index view
    # -------------------------------------------------------------------------------
    path('home/', views.index, name='index'),
    
    # class based index view
    # -------------------------------------------------------------------------------
    # path('home/', views.IndexClassView.as_view(), name='index'),
    
    # function based detail view
    # -------------------------------------------------------------------------------
    path('detail/<int:item_id>/', views.detail, name='detail'),
    
    # class based detail view
    # -------------------------------------------------------------------------------
    # path('detail/<int:pk>/', views.ProductsDetail.as_view(), name='detail'),
    
    # function based create item view
    # -------------------------------------------------------------------------------
    # path('add/', views.create_item, name='create_item'),
    
    # class based create item view
    # -------------------------------------------------------------------------------
    path('add/', views.CreateItem.as_view(), name='create_item'),
    
    # function based update item view
    # -------------------------------------------------------------------------------
    path('update/<int:id>/', views.update_item, name='update_item'),
    
    # function based delete item view
    # -------------------------------------------------------------------------------
    path('delete/<int:id>/', views.delete_item, name='delete_item'),
    
    #fuction based category
    path('category/<str:val>/', views.category, name='category'),
]

mysite/users/urls.py
from users import views
from django.urls import path

app_name = 'users'
urlpatterns = [

    # orders
    path('orders/<int:id>/<int:pdcd>/<str:user>/', views.Orders, name='orders'),
    
    # updating customer orders
    path('upd_orders/<int:id>/<int:upd_order_id>/', views.update_orders, name='upd_orders'),
    
    # customer rating-feedback view
    path('crf/<int:it_id>/<int:pc>/', views.CusRatFeed, name='CusRatFeed'),
    
    # updating customer ratings and feedbacks
    path('crf_upd/<int:details_id>/<int:crf_id>/', views.update_crf, name='upd_crf'),
    
    # deleting customer ratings and feedbacks
    path('del_crf/<int:details_id>/<int:crf_id>/', views.delete_crf, name='del_crf'),
    
    #paypal checkout button
    path('buy/<int:amt>/<int:qnt>/', views.Payment, name='buy'),

    #paYPAL on approve
    path('oa/', views.OnApprove, name='oa'),

    #paypal payment success
    path('ps/', views.PaymentSuccess, name='ps'),
]

mysite/products/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
category_choices = (
    ('MC', 'Mac'),
    ('ID', 'IPad'),
    ('IP', 'IPhone'),
    ('WT', 'Watch'),
    ('AP', 'Airpods'),
    ('TV', 'TV & Home'),
    ('ET', 'Entertainment'),
    ('AC', 'Accessories'),
)
class Item(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        default='1'
    )
    prod_code = models.IntegerField(default=100)
    for_user = models.CharField(max_length=50, default='xyz')
    item_name = models.CharField(max_length=50)
    item_desc = models.CharField(max_length=500, 
                                default='''Lorem, ipsum dolor sit amet consectetur adipisicing elit. A nam voluptate assumenda recusandae officia et consequatur, 
    nobis voluptatem incidunt laborum harum doloribus aspernatur iure aperiam adipisci quas alias ea delectus!''')
    item_price = models.IntegerField()
    item_image = models.CharField(
        max_length=500,
        default="https://assets.website-files.com/61ed56ae9da9fd7e0ef0a967/61f12e3a57bdb3717fbf9cec_Product_Default.svg"
    )
    
    category=models.CharField(choices=category_choices, max_length=2, null=True)
    
    def __str__(self):
        return self.item_name
    

class History(models.Model):

    user_name = models.CharField(max_length=100)
    prod_ref = models.IntegerField(default=100)
    item_name  = models.CharField(max_length=200)
    op_type = models.CharField(max_length=100)

    def __str__(self):
        return str(
            (
                self.prod_ref,
                self.user_name,
                self.item_name,
                self.op_type
            )
        )
        

mysite/products/forms.py
from django import forms
from products.models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['prod_code', 'for_user', 'item_name', 'item_desc', 'item_price', 'item_image']

mysite/products/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from products.models import Item
from products.forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from products.models import History
from users.models import CusOrders, CusRatingFeedback
from django.core.paginator import Paginator

# Create your views here.
# -------------------------------------------------------------------------------


# function based index view
# -------------------------------------------------------------------------------

def index(request):
    
    if request.user.is_superuser:
        itemlist = Item.objects.all()
        
        # for search functionality
        item_name = request.GET.get('item_name')
        if item_name != '' and item_name is not None:
            itemlist = Item.objects.filter(item_name__icontains=item_name)
            
        # For Pagination 
        paginator = Paginator(itemlist, 3)
        page = request.GET.get('page')
        itemlist = paginator.get_page(page)

    elif request.user.is_authenticated and request.user.profile.user_type=='store':
        itemlist = Item.objects.filter(for_user=request.user.username)
        
        # for search functionality
        item_name = request.GET.get('item_name')
        if item_name != '' and item_name is not None:
            itemlist = Item.objects.filter(item_name__icontains=item_name)
            
        # For Pagination 
        paginator = Paginator(itemlist, 3)
        page = request.GET.get('page')
        itemlist = paginator.get_page(page)

    elif request.user.is_authenticated and request.user.profile.user_type=='Cust':
        itemlist = Item.objects.all()
        
        # for search functionality
        item_name = request.GET.get('item_name')
        if item_name != '' and item_name is not None:
            itemlist = Item.objects.filter(item_name__icontains=item_name)
            
        # For Pagination 
        paginator = Paginator(itemlist, 3)
        page = request.GET.get('page')
        itemlist = paginator.get_page(page)

    else:
        itemlist = Item.objects.all()
        
        # for search functionality
        item_name = request.GET.get('item_name')
        if item_name != '' and item_name is not None:
            itemlist = Item.objects.filter(item_name__icontains=item_name)
            
        # For Pagination 
        paginator = Paginator(itemlist, 3)
        page = request.GET.get('page')
        itemlist = paginator.get_page(page)
    
    context = {
        'itemlist':itemlist
    }
    
    return render(request, 'products/index.html', context)


# class based index view
# -------------------------------------------------------------------------------

class IndexClassView(ListView):

    model = Item
    context_object_name = 'itemlist'
    template_name = 'products/index.html'


# function based detail view
# -------------------------------------------------------------------------------

def detail(request, item_id):
    item = Item.objects.get(pk=item_id)
    
    hist = History.objects.filter(
        prod_ref = item.prod_code
    )
    # store and admin
    if request.user.profile.user_type == 'store' or request.user.is_superuser:
        Obj_CusOrd = CusOrders.objects.filter(
            prod_code = item.prod_code
        )
        
    # customer
    elif request.user.profile.user_type == 'Cust':
        Obj_CusOrd = CusOrders.objects.filter(
            prod_code = item.prod_code,
            user = request.user.username
        )

    crf = CusRatingFeedback.objects.filter(
        prod_code=item.prod_code
    )

    context = {
        'item':item,
        'hist':hist,
        'oco': Obj_CusOrd,
        'crf':crf
    }

    return render(request, 'products/detail.html', context)


# class based detail view
# -------------------------------------------------------------------------------

class ProductsDetail(DetailView):

    model = Item
    context_object_name = 'item'
    template_name = 'products/detail.html'


# function based create item view
# -------------------------------------------------------------------------------

def create_item(request):
    
    form = ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('products:index')

    context = {
        'form':form
    }

    return render(request, 'products/item-form.html', context)


#class based create item view
# -------------------------------------------------------------------------------

class CreateItem(CreateView):

    model = Item
    fields = ['prod_code', 'for_user', 'item_name', 'item_desc', 'item_price', 'item_image']
    template_name = 'products/item-form.html'
    success_url = reverse_lazy('products:index')

    def form_valid(self, form):
        form.instance.user = self.request.user
        
        Obj_History = History(
            user_name = self.request.user.username,
            prod_ref = form.instance.prod_code,
            item_name = self.request.POST.get('item_name'),      # form.instance.item_name
            op_type = 'Created'
        )

        Obj_History.save()
        
        return super().form_valid(form)


# function based update item view
# -------------------------------------------------------------------------------

def update_item(request, id):
    
    item = Item.objects.get(pk=id)
    form = ItemForm(request.POST or None, instance=item)

    context = {
        'form':form
    }
    
    if form.is_valid():
        form.save()
        
        Obj_History = History(
            user_name = request.user.username,
            prod_ref = form.instance.prod_code,
            item_name = request.POST.get('item_name'),      # form.instance.item_name
            op_type = 'Updated'
        )

        Obj_History.save()
        
        return redirect('products:index')
    
    return render(request, 'products/item-form.html', context)


# function based delete item view
# -------------------------------------------------------------------------------

def delete_item(request, id):
    
    item = Item.objects.get(pk=id)
    
    context = {
        'item':item
    }
    
    if request.method == 'POST':
        
        Obj_History = History(
            user_name = request.user.username,
            prod_ref = item.prod_code,
            item_name = item.item_name,
            op_type = 'Deleted'
        )

        Obj_History.save()
        
        item.delete()
        return redirect('products:index')

    return render(request, 'products/item-delete.html', context)


def category(request, val):
    items = Item.objects.filter(
        category = val
    )
    
    context = {
        'items':items
    }
    
    return render(request, 'products/category.html', context)

mysite/products/templates/products/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'products/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://www.paypal.com/sdk/js?client-id=ATTaJADurJs_aKIXB4stVFTwUQDIsT4ZNsKLsKQlWwoFm3oR1lvfbtpP4Lx3QLYFMUcGuqqzGhidTNxj"></script>
</head>
<body>
    <nav class="navbar navbar-light bg-light">
        <a  href="{% url 'products:index' %}" class="navbar-brand">
            <img src="https://1000logos.net/wp-content/uploads/2016/10/Apple-Logo.png" style="width: 40px; height: 10; margin-top:5px; margin-left: 15px;" class="d-inline-block align-top" alt="">
        </a>

        <div class="navbar">
            {% if user.is_superuser %}
                <a href="#" class="nav-item nav-link btn btn-light">
                    Store
                </a>

                <a href="{% url 'products:category' 'MC' %}" class="nav-item nav-link btn btn-light">
                    Mac
                </a>

                <a href="{% url 'products:category' 'ID' %}" class="nav-item nav-link btn btn-light">
                    iPad
                </a>

                <a href="{% url 'products:category' 'IP' %}" class="nav-item nav-link btn btn-light">
                    iPhone
                </a>

                <a href="{% url 'products:category' 'WT' %}" class="nav-item nav-link btn btn-light">
                    Watch
                </a>

                <a href="{% url 'products:category' 'AP' %}" class="nav-item nav-link btn btn-light">
                    Airpods
                </a>

                <a href="{% url 'products:category' 'TV' %}" class="nav-item nav-link btn btn-light">
                    TV & Home
                </a>

                <a href="{% url 'products:category' 'ET' %}" class="nav-item nav-link btn btn-light">
                    Entertainment
                </a>

                <a href="{% url 'products:category' 'AC' %}" class="nav-item nav-link btn btn-light">
                    Accessories
                </a>

                {% comment %} this is for search functionality {% endcomment %}
                <form action="{% url 'products:index' %}" method="GET">
                    {% csrf_token %}
                    <span>
                        <input type="search" name="item_name" style="width:89px">
                        <button type="submit">Search</button>
                    </span>
                </form>

                <a href="{% url 'products:create_item' %}" class="nav-item nav-link btn btn-light">
                    Add Item
                </a>

                <a href="{% url 'profile' %}" class="nav-item nav-link btn btn-light">
                    Profile
                </a>

                <a href="{% url 'logout' %}" class="nav-item nav-link btn btn-light">
                    logout
                </a>
            
            {% elif user.is_authenticated %}
                <a href="#" class="nav-item nav-link btn btn-light">
                    Store
                </a>

                <a href="{% url 'products:category' 'MC' %}" class="nav-item nav-link btn btn-light">
                    Mac
                </a>

                <a href="{% url 'products:category' 'ID' %}" class="nav-item nav-link btn btn-light">
                    iPad
                </a>

                <a href="{% url 'products:category' 'IP' %}" class="nav-item nav-link btn btn-light">
                    iPhone
                </a>

                <a href="{% url 'products:category' 'WT' %}" class="nav-item nav-link btn btn-light">
                    Watch
                </a>

                <a href="{% url 'products:category' 'AP' %}" class="nav-item nav-link btn btn-light">
                    Airpods
                </a>

                <a href="{% url 'products:category' 'TV' %}" class="nav-item nav-link btn btn-light">
                    TV & Home
                </a>

                <a href="{% url 'products:category' 'ET' %}" class="nav-item nav-link btn btn-light">
                    Entertainment
                </a>

                <a href="{% url 'products:category' 'AC' %}" class="nav-item nav-link btn btn-light">
                    Accessories
                </a>

                {% comment %} this is for search functionality {% endcomment %}
                <form action="{% url 'products:index' %}" method="GET">
                    {% csrf_token %}
                    <span>
                        <input type="search" name="item_name" style="width:89px">
                        <button type="submit">Search</button>
                    </span>
                </form>

                <a href="{% url 'profile' %}" class="nav-item nav-link btn btn-light">
                    Profile
                </a>

                <a href="{% url 'logout' %}" class="nav-item nav-link btn btn-light">
                    logout
                </a>

            {% else %}
                <a href="#" class="nav-item nav-link btn btn-light">
                    Store
                </a>

                <a href="{% url 'products:category' 'MC' %}" class="nav-item nav-link btn btn-light">
                    Mac
                </a>

                <a href="{% url 'products:category' 'ID' %}" class="nav-item nav-link btn btn-light">
                    iPad
                </a>

                <a href="{% url 'products:category' 'IP' %}" class="nav-item nav-link btn btn-light">
                    iPhone
                </a>

                <a href="{% url 'products:category' 'WT' %}" class="nav-item nav-link btn btn-light">
                    Watch
                </a>

                <a href="{% url 'products:category' 'AP' %}" class="nav-item nav-link btn btn-light">
                    Airpods
                </a>

                <a href="{% url 'products:category' 'TV' %}" class="nav-item nav-link btn btn-light">
                    TV & Home
                </a>

                <a href="{% url 'products:category' 'ET' %}" class="nav-item nav-link btn btn-light">
                    Entertainment
                </a>

                <a href="{% url 'products:category' 'AC' %}" class="nav-item nav-link btn btn-light">
                    Accessories
                </a>

                {% comment %} this is for search functionality {% endcomment %}
                <form action="{% url 'products:index' %}" method="GET">
                    {% csrf_token %}
                    <span>
                        <input type="search" name="item_name" style="width:89px;border-radius:6px">
                        <button type="submit" style="width:61px; border-radius:30px; border:none;">Search</button>
                    </span>
                </form>

                <a href="{% url 'login' %}" class="nav-item nav-link btn btn-light">
                    Login
                </a>

                <a href="{% url 'register' %}" class="nav-item nav-link btn btn-light">
                    Sign Up
                </a>
            
            {% endif %}
        </div>


    </nav>


    {% if messages %}

        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}

    {% endif %}


    <div class="mb-5">

    </div>

    {% block body %}
    {% endblock %}

    
</body>
</html>

mysite/products/templates/products/category.html
{% extends 'products/base.html' %}

{% block body %}

    {% for obj in items %}

        <div class="row mb-3">
            <div class="col-md-3 offset-md-3">
                <img 
                    src="{{ obj.item_image }}"
                    class="card"
                    height="225px"
                    width="230px"
                >
            </div>

            <div class="col-md-3">
                <h3 style="font-size: 1.5rem;">
                    {{ obj.item_name }}
                </h3>

                <h5
                    style="font-style:italic;
                            font-size:1rem">
                    {{ obj.item_desc | truncatewords:6 }}
                </h5>

                <h6>
                    ${{ obj.item_price }}
                </h6>

            </div>

            <div class="col-md-3">

                
                {% if user.is_authenticated %}
                    
                    <a href="{% url 'products:detail' obj.id %}"
                        style="width:100px"
                        class="btn btn-success">

                        Details
                    </a>

                {% endif %}
            </div>
        </div>

    {% endfor %}
        
{% endblock %}

mysite/products/templates/products/detail.html
{% extends 'products/base.html' %}

{% block body %}

<div class="row">
    <div class="col-md-2 offset-md-2">
        <img height="250px"
            width="250px"
            class="card"
            src="{{ item.item_image }}">
    </div>

    <div class="col-md-2 offset-md-1">
        <h1
            style="font-style: italic;">
            {{ item.item_name }}
        </h1>

        <h2 style="font-style: italic;
                font-size: 1.3rem;
                text-align: justify;">
            {{ item.item_desc }}
        </h2>

        <h3>
            ${{ item.item_price }}
        </h3>
    </div>

    <div class="col-md-3 offset-md-1">

        
        {% if user.is_superuser %}
            
            <a href="{% url 'products:update_item' item.id %}"
                style="width:80px"
                class="btn btn-warning">
                Edit
            </a>

            <a href="{% url 'products:delete_item' item.id %}"
                style="width:80px"
                class="btn btn-danger">
                Delete
            </a>

            <a href="{% url 'products:index' %}"
                style="width:80px"
                class="btn btn-success">
                Back
            </a>
        {% elif user.is_authenticated and user.profile.user_type == 'store' %}

            <a href="{% url 'products:update_item' item.id %}"
                style="width:80px"
                class="btn btn-warning">
                Edit
            </a>

            <a href="{% url 'products:index' %}"
                style="width:80px"
                class="btn btn-success">
                Back
            </a>

        {% elif user.is_authenticated and user.profile.user_type == 'Cust' %}

            <a href="{% url 'users:orders' item.id item.prod_code user.username %}"
                style="width:80px"
                class="btn btn-warning">
                Order
            </a>

            <a href="{% url 'products:index' %}"
                style="width:80px"
                class="btn btn-success">
                Back
            </a>


        
        {% endif %}
    </div>
</div>


{% if user.is_authenticated %}

    {% if user.profile.user_type == 'store' or user.profile.user_type == 'Admin' %}

        {% for obj in hist %}

            <div
                class="row mb-1">

                <div
                    class="col-md-8
                        offset-md-2
                        bg-danger
                        text-white">

                        <div
                            class="row">

                            <div 
                                class="col-md-3 
                                    text-left">

                                {{ obj.user_name }}
                            </div>

                            <div 
                                class="col-md-3 
                                    text-left">

                                {{ obj.prod_ref }}
                            </div>

                            <div 
                                class="col-md-3 
                                    text-left">

                                {{ obj.item_name }}
                            </div>

                            <div 
                                class="col-md-3 
                                    text-left">

                                {{ obj.op_type }}
                            </div>
                        </div>
                </div>

                <div
                    class="col-md-2">

                </div>

            </div>

        {% endfor %}

    {% endif %}

    <!-- green -->

    {% if user.profile.user_type == 'store' or user.profile.user_type == 'Cust' or user.profile.user_type == 'Admin' %}

        {% for obj in oco %}

            <div
                class="row mb-3">

                <div
                    class="col-md-8
                        offset-md-2
                        bg-success
                        text-white">

                        <div
                            class="row">

                            <div 
                                class="col-md-2 
                                    text-left">

                                {{ obj.order_id }}
                            </div>

                            <div 
                                class="col-md-2 
                                    text-left">

                                {{ obj.prod_code }}
                            </div>

                            <div 
                                class="col-md-2 
                                    text-left">

                                {{ obj.quantity }}
                            </div>

                            <div 
                                class="col-md-2 
                                    text-left">

                                {{ obj.user }}
                            </div>

                            <div 
                                class="col-md-2 
                                    text-left">

                                {% if user.profile.user_type == 'Cust' %}
                                    <a
                                        class="btn btn-warning btn-sm"
                                        href="{% url 'users:upd_orders' item.id obj.order_id %}">

                                        Edit Qty
                                    </a>
                                {% endif %}
                            </div>

                            <div 
                                class="col-md-2 
                                    text-left">

                                {% if user.profile.user_type == 'Cust' %}
                                    <a
                                        class="btn btn-primary btn-sm"
                                        href="{% url 'users:buy' item.item_price obj.quantity %}">
                                            Buy Now
                                    </a>
                                {% endif %}
                            </div>
                        </div>
                </div>

                <div
                    class="col-md-2">

                </div>

            </div>

        {% endfor %}

    {% endif %}

    <!-- add feedback and ratings button -->

    {% if user.profile.user_type == 'Cust' %}
    <a class="btn btn-dark offset-md-5 mb-2" href="{% url 'users:CusRatFeed' item.id item.prod_code %}">
        Add Ratings and Feedback
    </a>
    {% endif %}

    <!-- blue -->

    {% if user.profile.user_type == 'store' or user.profile.user_type == 'Cust' or user.profile.user_type == 'Admin' %}

        {% for obj in crf %}

            <div
                class="row mb-1">

                <div
                    class="col-md-8
                        offset-md-2
                        bg-info
                        text-white">

                        <div
                            class="row">

                            <div 
                                class="col-md-1 
                                    text-left">

                                {{ obj.prod_code }}
                            </div>

                            <div 
                                class="col-md-1 
                                    text-left">

                                {{ obj.ratings }}
                            </div>

                            <div 
                                class="col-md-2 
                                    text-left">

                                {{ obj.feedback }}
                            </div>

                            <div 
                                class="col-md-2 
                                    text-left">

                                {{ obj.username }}
                            </div>

                            <div 
                                class="col-md-2 
                                    text-left">

                                {{ obj.user_type }}
                            </div>

                            <div 
                                class="col-md-2 
                                    text-left">

                                {% if obj.username == user.username %}
                                    <a
                                        class="btn btn-warning btn-sm"
                                        href="{% url 'users:upd_crf' item.id obj.id %}">

                                        Edit
                                    </a>
                                {% endif %}
                            </div>

                            <div 
                                class="col-md-2 
                                    text-left">

                                {% if obj.username == user.username %}
                                    <a
                                        class="btn btn-primary btn-sm"
                                        href="{% url 'users:del_crf' item.id obj.id %}">

                                        Delete
                                    </a>
                                {% endif %}
                            </div>
                        </div>
                </div>

                <div
                    class="col-md-2">

                </div>

            </div>

        {% endfor %}

    {% endif %}

{% endif %}

{% endblock %}

mysite/products/templates/products/item-delete.html
{% extends 'products/base.html' %}

{% block body %}

<form method="POST">
    {% csrf_token %}
    <h3>Are you sure you want to delete, {{ item.item_name }}</h3>
    <button type="submit">Confirm</button>
</form>

{% endblock %}